package io.github.xxfast.kotlin.native.nuget.processor.cir

internal fun StringBuilder.renderFuncNativeHelper(helper: CirFuncNativeHelper) {
  val hasArgs: Boolean = helper.arities.any { it > 0 }

  appendLine("    internal static class NugetFuncNative")
  appendLine("    {")

  for (arity in helper.arities.sorted()) {
    val paramStr: String = (listOf("IntPtr handle") +
      (0 until arity).map { "IntPtr arg$it" }).joinToString(", ")

    appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_func${arity}_invoke\")]")
    appendLine("        internal static extern IntPtr Invoke$arity($paramStr);")
    appendLine()
  }

  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_dispose\")]")
  appendLine("        internal static extern void Dispose(IntPtr handle);")

  if (hasArgs) {
    appendLine()
    appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_string\")]")
    appendLine("        private static extern IntPtr wrap_string(string value);")
    appendLine()
    appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_int\")]")
    appendLine("        private static extern IntPtr wrap_int(int value);")
    appendLine()
    appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_long\")]")
    appendLine("        private static extern IntPtr wrap_long(long value);")
    appendLine()
    appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_float\")]")
    appendLine("        private static extern IntPtr wrap_float(float value);")
    appendLine()
    appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_double\")]")
    appendLine("        private static extern IntPtr wrap_double(double value);")
    appendLine()
    appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_bool\")]")
    appendLine("        private static extern IntPtr wrap_bool(bool value);")
    appendLine()
    appendLine("        internal static IntPtr WrapArg<T>(T value)")
    appendLine("        {")
    appendLine("            if (typeof(T) == typeof(string)) return wrap_string((string)(object)value!);")
    appendLine("            if (typeof(T) == typeof(int)) return wrap_int((int)(object)value!);")
    appendLine("            if (typeof(T) == typeof(long)) return wrap_long((long)(object)value!);")
    appendLine("            if (typeof(T) == typeof(float)) return wrap_float((float)(object)value!);")
    appendLine("            if (typeof(T) == typeof(double)) return wrap_double((double)(object)value!);")
    appendLine("            if (typeof(T) == typeof(bool)) return wrap_bool((bool)(object)value!);")
    appendLine("            var field = typeof(T).GetField(\"_handle\",")
    appendLine("                System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Public);")
    appendLine("            if (field != null) return (IntPtr)field.GetValue(value)!;")
    appendLine("            throw new NotSupportedException($\"Cannot wrap {typeof(T).Name} as lambda argument\");")
    appendLine("        }")
  }

  appendLine("    }")
  appendLine()
}

internal fun StringBuilder.renderFuncHelper(helper: CirFuncHelper) {
  val ns: String = helper.helperNamespace
  val marshalRef: String = "$ns.NugetMarshal"
  val funcNativeRef: String = "$ns.NugetFuncNative"

  for (arity in helper.arities.sorted()) {
    if (arity == 0) {
      appendLine("    public class KotlinFunc<TResult> : IDisposable")
      appendLine("    {")
      appendLine("        internal IntPtr _handle;")
      appendLine()
      appendLine("        internal KotlinFunc(IntPtr handle) { _handle = handle; }")
      appendLine()
      appendLine("        public TResult Invoke()")
      appendLine("        {")
      appendLine("            IntPtr result = $funcNativeRef.Invoke0(_handle);")
      appendLine("            return $marshalRef.FromHandle<TResult>(result);")
      appendLine("        }")
      appendLine()
      appendLine("        public void Dispose()")
      appendLine("        {")
      appendLine("            if (_handle != IntPtr.Zero)")
      appendLine("            {")
      appendLine("                $funcNativeRef.Dispose(_handle);")
      appendLine("                _handle = IntPtr.Zero;")
      appendLine("            }")
      appendLine("        }")
      appendLine("    }")
      appendLine()
    } else {
      val typeParams: String = (1..arity).map { "T$it" }.plus("TResult").joinToString(", ")
      val methodParams: String = (1..arity).map { "T$it arg${it - 1}" }.joinToString(", ")
      val invokeArgs: String = (listOf("_handle") + (0 until arity).map { "boxedArg$it" }).joinToString(", ")

      appendLine("    public class KotlinFunc<$typeParams> : IDisposable")
      appendLine("    {")
      appendLine("        internal IntPtr _handle;")
      appendLine()
      appendLine("        internal KotlinFunc(IntPtr handle) { _handle = handle; }")
      appendLine()
      appendLine("        public TResult Invoke($methodParams)")
      appendLine("        {")
      for (i in 0 until arity) {
        appendLine("            IntPtr boxedArg$i = $funcNativeRef.WrapArg<T${i + 1}>(arg$i);")
      }
      appendLine("            IntPtr result = $funcNativeRef.Invoke$arity($invokeArgs);")
      appendLine("            return $marshalRef.FromHandle<TResult>(result);")
      appendLine("        }")
      appendLine()
      appendLine("        public void Dispose()")
      appendLine("        {")
      appendLine("            if (_handle != IntPtr.Zero)")
      appendLine("            {")
      appendLine("                $funcNativeRef.Dispose(_handle);")
      appendLine("                _handle = IntPtr.Zero;")
      appendLine("            }")
      appendLine("        }")
      appendLine("    }")
      appendLine()
    }
  }
}

internal fun StringBuilder.renderSuspendFuncNativeHelper(helper: CirSuspendFuncNativeHelper) {
  val hasArgs: Boolean = helper.arities.any { it > 0 }

  appendLine("    internal static class NugetSuspendFuncNative")
  appendLine("    {")

  for (arity in helper.arities.sorted()) {
    val paramStr: String = (listOf("IntPtr handle") +
      (0 until arity).map { "IntPtr arg$it" } +
      listOf("NugetAsyncCallback callback", "IntPtr userData")).joinToString(", ")

    appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_suspend_func${arity}_invoke\")]")
    appendLine("        internal static extern IntPtr Invoke$arity($paramStr);")
    appendLine()
  }

  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_dispose\")]")
  appendLine("        internal static extern void Dispose(IntPtr handle);")

  if (hasArgs) {
    appendLine()
    appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_string\")]")
    appendLine("        private static extern IntPtr wrap_string(string value);")
    appendLine()
    appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_int\")]")
    appendLine("        private static extern IntPtr wrap_int(int value);")
    appendLine()
    appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_long\")]")
    appendLine("        private static extern IntPtr wrap_long(long value);")
    appendLine()
    appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_float\")]")
    appendLine("        private static extern IntPtr wrap_float(float value);")
    appendLine()
    appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_double\")]")
    appendLine("        private static extern IntPtr wrap_double(double value);")
    appendLine()
    appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_bool\")]")
    appendLine("        private static extern IntPtr wrap_bool(bool value);")
    appendLine()
    appendLine("        internal static IntPtr WrapArg<T>(T value)")
    appendLine("        {")
    appendLine("            if (typeof(T) == typeof(string)) return wrap_string((string)(object)value!);")
    appendLine("            if (typeof(T) == typeof(int)) return wrap_int((int)(object)value!);")
    appendLine("            if (typeof(T) == typeof(long)) return wrap_long((long)(object)value!);")
    appendLine("            if (typeof(T) == typeof(float)) return wrap_float((float)(object)value!);")
    appendLine("            if (typeof(T) == typeof(double)) return wrap_double((double)(object)value!);")
    appendLine("            if (typeof(T) == typeof(bool)) return wrap_bool((bool)(object)value!);")
    appendLine("            var field = typeof(T).GetField(\"_handle\",")
    appendLine("                System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Public);")
    appendLine("            if (field != null) return (IntPtr)field.GetValue(value)!;")
    appendLine("            throw new NotSupportedException(\$\"Cannot wrap {typeof(T).Name} as lambda argument\");")
    appendLine("        }")
  }

  appendLine("    }")
  appendLine()
}

internal fun StringBuilder.renderSuspendFuncHelper(helper: CirSuspendFuncHelper) {
  val ns: String = helper.helperNamespace
  val marshalRef: String = "$ns.NugetMarshal"
  val funcNativeRef: String = "$ns.NugetSuspendFuncNative"

  for (arity in helper.arities.sorted()) {
    // Generate KotlinSuspendFunc variants (non-Unit)
    if (arity == 0) {
      appendLine("    public class KotlinSuspendFunc<TResult> : IDisposable")
      appendLine("    {")
      appendLine("        internal IntPtr _handle;")
      appendLine()
      appendLine("        internal KotlinSuspendFunc(IntPtr handle) { _handle = handle; }")
      appendLine()
      appendLine("        public Task<TResult> InvokeAsync(CancellationToken cancellationToken = default)")
      appendLine("        {")
      appendLine("            var tcs = new TaskCompletionSource<TResult>(TaskCreationOptions.RunContinuationsAsynchronously);")
      appendLine("            GCHandle tcsHandle = GCHandle.Alloc(tcs);")
      appendLine("            NugetAsyncCallback callback = null!;")
      appendLine("            GCHandle callbackHandle = default;")
      appendLine("            CancellationTokenRegistration reg = default;")
      appendLine("            IntPtr jobHandle = IntPtr.Zero;")
      appendLine("            callback = (resultPtr, errorPtr, isCancelled, userData) =>")
      appendLine("            {")
      appendLine("                reg.Dispose();")
      appendLine("                NugetJobNative.Dispose(jobHandle);")
      appendLine("                callbackHandle.Free();")
      appendLine("                var t = (TaskCompletionSource<TResult>)GCHandle.FromIntPtr(userData).Target!;")
      appendLine("                GCHandle.FromIntPtr(userData).Free();")
      appendLine("                if (isCancelled != 0)")
      appendLine("                {")
      appendLine("                    t.TrySetCanceled(cancellationToken);")
      appendLine("                }")
      appendLine("                else if (errorPtr != IntPtr.Zero)")
      appendLine("                {")
      appendLine("                    t.SetException(NugetErrorNative.BuildException(errorPtr));")
      appendLine("                }")
      appendLine("                else")
      appendLine("                {")
      appendLine("                    t.SetResult($marshalRef.FromHandle<TResult>(resultPtr));")
      appendLine("                }")
      appendLine("            };")
      appendLine("            callbackHandle = GCHandle.Alloc(callback);")
      appendLine("            jobHandle = $funcNativeRef.Invoke0(_handle, callback, GCHandle.ToIntPtr(tcsHandle));")
      appendLine("            if (cancellationToken.CanBeCanceled)")
      appendLine("                reg = cancellationToken.Register(() => NugetJobNative.Cancel(jobHandle));")
      appendLine("            return tcs.Task;")
      appendLine("        }")
      appendLine()
      appendLine("        public void Dispose()")
      appendLine("        {")
      appendLine("            if (_handle != IntPtr.Zero)")
      appendLine("            {")
      appendLine("                $funcNativeRef.Dispose(_handle);")
      appendLine("                _handle = IntPtr.Zero;")
      appendLine("            }")
      appendLine("        }")
      appendLine("    }")
      appendLine()
    } else {
      val typeParams: String = (1..arity).map { "T$it" }.plus("TResult").joinToString(", ")
      val methodParams: String = (1..arity).map { "T$it arg${it - 1}" }.joinToString(", ")
      val invokeArgs: String = (listOf("_handle") +
        (0 until arity).map { "boxedArg$it" } +
        listOf("callback", "GCHandle.ToIntPtr(tcsHandle)")).joinToString(", ")

      appendLine("    public class KotlinSuspendFunc<$typeParams> : IDisposable")
      appendLine("    {")
      appendLine("        internal IntPtr _handle;")
      appendLine()
      appendLine("        internal KotlinSuspendFunc(IntPtr handle) { _handle = handle; }")
      appendLine()
      appendLine("        public Task<TResult> InvokeAsync($methodParams, CancellationToken cancellationToken = default)")
      appendLine("        {")
      appendLine("            var tcs = new TaskCompletionSource<TResult>(TaskCreationOptions.RunContinuationsAsynchronously);")
      appendLine("            GCHandle tcsHandle = GCHandle.Alloc(tcs);")
      appendLine("            NugetAsyncCallback callback = null!;")
      appendLine("            GCHandle callbackHandle = default;")
      appendLine("            CancellationTokenRegistration reg = default;")
      appendLine("            IntPtr jobHandle = IntPtr.Zero;")
      appendLine("            callback = (resultPtr, errorPtr, isCancelled, userData) =>")
      appendLine("            {")
      appendLine("                reg.Dispose();")
      appendLine("                NugetJobNative.Dispose(jobHandle);")
      appendLine("                callbackHandle.Free();")
      appendLine("                var t = (TaskCompletionSource<TResult>)GCHandle.FromIntPtr(userData).Target!;")
      appendLine("                GCHandle.FromIntPtr(userData).Free();")
      appendLine("                if (isCancelled != 0)")
      appendLine("                {")
      appendLine("                    t.TrySetCanceled(cancellationToken);")
      appendLine("                }")
      appendLine("                else if (errorPtr != IntPtr.Zero)")
      appendLine("                {")
      appendLine("                    t.SetException(NugetErrorNative.BuildException(errorPtr));")
      appendLine("                }")
      appendLine("                else")
      appendLine("                {")
      appendLine("                    t.SetResult($marshalRef.FromHandle<TResult>(resultPtr));")
      appendLine("                }")
      appendLine("            };")
      appendLine("            callbackHandle = GCHandle.Alloc(callback);")
      for (i in 0 until arity) {
        appendLine("            IntPtr boxedArg$i = $funcNativeRef.WrapArg<T${i + 1}>(arg$i);")
      }
      appendLine("            jobHandle = $funcNativeRef.Invoke$arity($invokeArgs);")
      appendLine("            if (cancellationToken.CanBeCanceled)")
      appendLine("                reg = cancellationToken.Register(() => NugetJobNative.Cancel(jobHandle));")
      appendLine("            return tcs.Task;")
      appendLine("        }")
      appendLine()
      appendLine("        public void Dispose()")
      appendLine("        {")
      appendLine("            if (_handle != IntPtr.Zero)")
      appendLine("            {")
      appendLine("                $funcNativeRef.Dispose(_handle);")
      appendLine("                _handle = IntPtr.Zero;")
      appendLine("            }")
      appendLine("        }")
      appendLine("    }")
      appendLine()
    }

    // Generate KotlinSuspendAction variants (Unit)
    if (arity == 0) {
      appendLine("    public class KotlinSuspendAction : IDisposable")
      appendLine("    {")
      appendLine("        internal IntPtr _handle;")
      appendLine()
      appendLine("        internal KotlinSuspendAction(IntPtr handle) { _handle = handle; }")
      appendLine()
      appendLine("        public Task InvokeAsync(CancellationToken cancellationToken = default)")
      appendLine("        {")
      appendLine("            var tcs = new TaskCompletionSource<bool>(TaskCreationOptions.RunContinuationsAsynchronously);")
      appendLine("            GCHandle tcsHandle = GCHandle.Alloc(tcs);")
      appendLine("            NugetAsyncCallback callback = null!;")
      appendLine("            GCHandle callbackHandle = default;")
      appendLine("            CancellationTokenRegistration reg = default;")
      appendLine("            IntPtr jobHandle = IntPtr.Zero;")
      appendLine("            callback = (resultPtr, errorPtr, isCancelled, userData) =>")
      appendLine("            {")
      appendLine("                reg.Dispose();")
      appendLine("                NugetJobNative.Dispose(jobHandle);")
      appendLine("                callbackHandle.Free();")
      appendLine("                var t = (TaskCompletionSource<bool>)GCHandle.FromIntPtr(userData).Target!;")
      appendLine("                GCHandle.FromIntPtr(userData).Free();")
      appendLine("                if (isCancelled != 0)")
      appendLine("                {")
      appendLine("                    t.TrySetCanceled(cancellationToken);")
      appendLine("                }")
      appendLine("                else if (errorPtr != IntPtr.Zero)")
      appendLine("                {")
      appendLine("                    t.SetException(NugetErrorNative.BuildException(errorPtr));")
      appendLine("                }")
      appendLine("                else")
      appendLine("                {")
      appendLine("                    t.SetResult(true);")
      appendLine("                }")
      appendLine("            };")
      appendLine("            callbackHandle = GCHandle.Alloc(callback);")
      appendLine("            jobHandle = $funcNativeRef.Invoke0(_handle, callback, GCHandle.ToIntPtr(tcsHandle));")
      appendLine("            if (cancellationToken.CanBeCanceled)")
      appendLine("                reg = cancellationToken.Register(() => NugetJobNative.Cancel(jobHandle));")
      appendLine("            return tcs.Task;")
      appendLine("        }")
      appendLine()
      appendLine("        public void Dispose()")
      appendLine("        {")
      appendLine("            if (_handle != IntPtr.Zero)")
      appendLine("            {")
      appendLine("                $funcNativeRef.Dispose(_handle);")
      appendLine("                _handle = IntPtr.Zero;")
      appendLine("            }")
      appendLine("        }")
      appendLine("    }")
      appendLine()
    } else {
      val typeParams: String = (1..arity).map { "T$it" }.joinToString(", ")
      val methodParams: String = (1..arity).map { "T$it arg${it - 1}" }.joinToString(", ")
      val invokeArgs: String = (listOf("_handle") +
        (0 until arity).map { "boxedArg$it" } +
        listOf("callback", "GCHandle.ToIntPtr(tcsHandle)")).joinToString(", ")

      appendLine("    public class KotlinSuspendAction<$typeParams> : IDisposable")
      appendLine("    {")
      appendLine("        internal IntPtr _handle;")
      appendLine()
      appendLine("        internal KotlinSuspendAction(IntPtr handle) { _handle = handle; }")
      appendLine()
      appendLine("        public Task InvokeAsync($methodParams, CancellationToken cancellationToken = default)")
      appendLine("        {")
      appendLine("            var tcs = new TaskCompletionSource<bool>(TaskCreationOptions.RunContinuationsAsynchronously);")
      appendLine("            GCHandle tcsHandle = GCHandle.Alloc(tcs);")
      appendLine("            NugetAsyncCallback callback = null!;")
      appendLine("            GCHandle callbackHandle = default;")
      appendLine("            CancellationTokenRegistration reg = default;")
      appendLine("            IntPtr jobHandle = IntPtr.Zero;")
      appendLine("            callback = (resultPtr, errorPtr, isCancelled, userData) =>")
      appendLine("            {")
      appendLine("                reg.Dispose();")
      appendLine("                NugetJobNative.Dispose(jobHandle);")
      appendLine("                callbackHandle.Free();")
      appendLine("                var t = (TaskCompletionSource<bool>)GCHandle.FromIntPtr(userData).Target!;")
      appendLine("                GCHandle.FromIntPtr(userData).Free();")
      appendLine("                if (isCancelled != 0)")
      appendLine("                {")
      appendLine("                    t.TrySetCanceled(cancellationToken);")
      appendLine("                }")
      appendLine("                else if (errorPtr != IntPtr.Zero)")
      appendLine("                {")
      appendLine("                    t.SetException(NugetErrorNative.BuildException(errorPtr));")
      appendLine("                }")
      appendLine("                else")
      appendLine("                {")
      appendLine("                    t.SetResult(true);")
      appendLine("                }")
      appendLine("            };")
      appendLine("            callbackHandle = GCHandle.Alloc(callback);")
      for (i in 0 until arity) {
        appendLine("            IntPtr boxedArg$i = $funcNativeRef.WrapArg<T${i + 1}>(arg$i);")
      }
      appendLine("            jobHandle = $funcNativeRef.Invoke$arity($invokeArgs);")
      appendLine("            if (cancellationToken.CanBeCanceled)")
      appendLine("                reg = cancellationToken.Register(() => NugetJobNative.Cancel(jobHandle));")
      appendLine("            return tcs.Task;")
      appendLine("        }")
      appendLine()
      appendLine("        public void Dispose()")
      appendLine("        {")
      appendLine("            if (_handle != IntPtr.Zero)")
      appendLine("            {")
      appendLine("                $funcNativeRef.Dispose(_handle);")
      appendLine("                _handle = IntPtr.Zero;")
      appendLine("            }")
      appendLine("        }")
      appendLine("    }")
      appendLine()
    }
  }
}

