package io.github.xxfast.kotlin.native.nuget.processor.cir

internal fun StringBuilder.renderFlowHelper(helper: CirFlowHelper) {
  appendLine("    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]")
  appendLine("    internal delegate void NugetFlowOnNextCallback(IntPtr itemPtr, byte isCancelled, IntPtr userData);")
  appendLine()
  appendLine("    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]")
  appendLine("    internal delegate void NugetFlowOnCompleteCallback(IntPtr userData);")
  appendLine()
  appendLine("    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]")
  appendLine("    internal delegate void NugetFlowOnErrorCallback(IntPtr errorPtr, IntPtr userData);")
  appendLine()
  appendLine("    internal delegate IntPtr NugetFlowCollectDelegate(IntPtr onNext, IntPtr onComplete, IntPtr onError, IntPtr userData);")
  appendLine()
  appendLine("    public class KotlinFlow<T> : IAsyncEnumerable<T>")
  appendLine("    {")
  appendLine("        private readonly NugetFlowCollectDelegate _startCollect;")
  appendLine()
  appendLine("        internal KotlinFlow(NugetFlowCollectDelegate startCollect)")
  appendLine("        {")
  appendLine("            _startCollect = startCollect;")
  appendLine("        }")
  appendLine()
  appendLine("        public IAsyncEnumerator<T> GetAsyncEnumerator(CancellationToken cancellationToken = default)")
  appendLine("            => new KotlinFlowEnumerator<T>(_startCollect, cancellationToken);")
  appendLine("    }")
  appendLine()
  appendLine("    internal class KotlinFlowEnumerator<T> : IAsyncEnumerator<T>")
  appendLine("    {")
  appendLine("        private readonly Channel<T> _channel;")
  appendLine("        private readonly CancellationTokenRegistration _cancelReg;")
  appendLine("        private IntPtr _jobHandle;")
  appendLine("        private GCHandle _onNextHandle;")
  appendLine("        private GCHandle _onCompleteHandle;")
  appendLine("        private GCHandle _onErrorHandle;")
  appendLine("        private bool _done;")
  appendLine()
  appendLine("        public T Current { get; private set; } = default!;")
  appendLine()
  appendLine("        internal KotlinFlowEnumerator(NugetFlowCollectDelegate startCollect, CancellationToken cancellationToken)")
  appendLine("        {")
  appendLine("            _channel = Channel.CreateUnbounded<T>(new UnboundedChannelOptions { SingleReader = true, SingleWriter = true });")
  appendLine()
  appendLine("            NugetFlowOnNextCallback onNext = (itemPtr, isCancelled, userData) =>")
  appendLine("            {")
  appendLine("                if (isCancelled != 0) { _channel.Writer.TryComplete(); return; }")
  appendLine("                T value = NugetMarshal.FromHandle<T>(itemPtr);")
  appendLine("                _channel.Writer.TryWrite(value);")
  appendLine("            };")
  appendLine()
  appendLine("            NugetFlowOnCompleteCallback onComplete = (userData) =>")
  appendLine("            {")
  appendLine("                _channel.Writer.TryComplete();")
  appendLine("            };")
  appendLine()
  appendLine("            NugetFlowOnErrorCallback onError = (errorPtr, userData) =>")
  appendLine("            {")
  appendLine("                _channel.Writer.TryComplete(NugetErrorNative.BuildException(errorPtr));")
  appendLine("            };")
  appendLine()
  appendLine("            _onNextHandle = GCHandle.Alloc(onNext);")
  appendLine("            _onCompleteHandle = GCHandle.Alloc(onComplete);")
  appendLine("            _onErrorHandle = GCHandle.Alloc(onError);")
  appendLine()
  appendLine("            IntPtr onNextPtr = Marshal.GetFunctionPointerForDelegate(onNext);")
  appendLine("            IntPtr onCompletePtr = Marshal.GetFunctionPointerForDelegate(onComplete);")
  appendLine("            IntPtr onErrorPtr = Marshal.GetFunctionPointerForDelegate(onError);")
  appendLine()
  appendLine("            _jobHandle = startCollect(onNextPtr, onCompletePtr, onErrorPtr, IntPtr.Zero);")
  appendLine()
  appendLine("            if (cancellationToken.CanBeCanceled)")
  appendLine("                _cancelReg = cancellationToken.Register(() => NugetJobNative.Cancel(_jobHandle));")
  appendLine("        }")
  appendLine()
  appendLine("        public async ValueTask<bool> MoveNextAsync()")
  appendLine("        {")
  appendLine("            if (_done) return false;")
  appendLine()
  appendLine("            try")
  appendLine("            {")
  appendLine("                if (await _channel.Reader.WaitToReadAsync())")
  appendLine("                {")
  appendLine("                    if (_channel.Reader.TryRead(out T? item))")
  appendLine("                    {")
  appendLine("                        Current = item;")
  appendLine("                        return true;")
  appendLine("                    }")
  appendLine("                }")
  appendLine("            }")
  appendLine("            catch (ChannelClosedException)")
  appendLine("            {")
  appendLine("                _done = true;")
  appendLine("                if (_channel.Reader.Completion.IsFaulted)")
  appendLine("                {")
  appendLine("                    var ex = _channel.Reader.Completion.Exception?.InnerException;")
  appendLine("                    if (ex != null) throw ex;")
  appendLine("                }")
  appendLine("                return false;")
  appendLine("            }")
  appendLine()
  appendLine("            _done = true;")
  appendLine()
  appendLine("            if (_channel.Reader.Completion.IsFaulted)")
  appendLine("            {")
  appendLine("                var ex = _channel.Reader.Completion.Exception?.InnerException;")
  appendLine("                if (ex != null) throw ex;")
  appendLine("            }")
  appendLine()
  appendLine("            return false;")
  appendLine("        }")
  appendLine()
  appendLine("        public ValueTask DisposeAsync()")
  appendLine("        {")
  appendLine("            _cancelReg.Dispose();")
  appendLine("            if (_jobHandle != IntPtr.Zero)")
  appendLine("            {")
  appendLine("                NugetJobNative.Cancel(_jobHandle);")
  appendLine("                NugetJobNative.Dispose(_jobHandle);")
  appendLine("                _jobHandle = IntPtr.Zero;")
  appendLine("            }")
  appendLine("            if (_onNextHandle.IsAllocated) _onNextHandle.Free();")
  appendLine("            if (_onCompleteHandle.IsAllocated) _onCompleteHandle.Free();")
  appendLine("            if (_onErrorHandle.IsAllocated) _onErrorHandle.Free();")
  appendLine("            _channel.Writer.TryComplete();")
  appendLine("            return ValueTask.CompletedTask;")
  appendLine("        }")
  appendLine("    }")
  appendLine()

  if (helper.includesStateFlow) {
    // ADR-065: KotlinStateFlow<T> IS-A KotlinFlow<T> -- it inherits the entire collect/enumerator/
    // cancellation/error machinery above unchanged and adds only a synchronous `Value` read.
    appendLine("    public class KotlinStateFlow<T> : KotlinFlow<T>")
    appendLine("    {")
    appendLine("        private readonly Func<IntPtr> _readValue;")
    appendLine()
    appendLine("        internal KotlinStateFlow(NugetFlowCollectDelegate startCollect, Func<IntPtr> readValue)")
    appendLine("            : base(startCollect)")
    appendLine("        {")
    appendLine("            _readValue = readValue;")
    appendLine("        }")
    appendLine()
    appendLine("        public T Value => NugetMarshal.FromHandle<T>(_readValue());")
    appendLine("    }")
    appendLine()
  }
}

internal fun StringBuilder.renderFlowMethod(method: CirMethod, className: String) {
  if (method.isStateFlow) {
    renderStateFlowMethod(method, className)
    return
  }

  val paramStr: String = method.parameters.joinToString(", ") { "${it.type} ${it.name}" }
  val nativeName: String = method.nativeName

  appendLine("        public KotlinFlow<${method.flowElementType}> ${method.name}($paramStr)")
  appendLine("        {")
  appendLine("            if (_handle == IntPtr.Zero)")
  appendLine("                throw new ObjectDisposedException(nameof($className));")
  appendLine("            return new KotlinFlow<${method.flowElementType}>((onNext, onComplete, onError, userData) =>")
  appendLine("                $nativeName(${method.body}));")
  appendLine("        }")
  appendLine()
}

// ADR-065: StateFlow<T> as a non-suspend function return. Identical to renderFlowMethod's
// `_collect` wiring, plus a synchronous `_value` read passed as the second KotlinStateFlow<T>
// constructor argument (the method's own parameters, re-read on each `.Value` access).
internal fun StringBuilder.renderStateFlowMethod(method: CirMethod, className: String) {
  val paramStr: String = method.parameters.joinToString(", ") { "${it.type} ${it.name}" }
  val paramNames: String = method.parameters.joinToString(", ") { it.name }
  val nativeName: String = method.nativeName
  val valueNativeName: String = method.stateFlowValueNativeName
  val valueCallArgs: String = if (paramNames.isEmpty()) "_handle" else "_handle, $paramNames"

  appendLine("        public KotlinStateFlow<${method.flowElementType}> ${method.name}($paramStr)")
  appendLine("        {")
  appendLine("            if (_handle == IntPtr.Zero)")
  appendLine("                throw new ObjectDisposedException(nameof($className));")
  appendLine("            return new KotlinStateFlow<${method.flowElementType}>((onNext, onComplete, onError, userData) =>")
  appendLine("                $nativeName(${method.body}),")
  appendLine("                () => $valueNativeName($valueCallArgs));")
  appendLine("        }")
  appendLine()
}

