package io.github.xxfast.kotlin.native.nuget.processor.cir

internal fun StringBuilder.renderMarshalHelper(helper: CirMarshalHelper) {
  appendLine("    internal static class NugetMarshal")
  appendLine("    {")
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_string\")]")
  appendLine("        private static extern IntPtr Native_unwrap_string(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_byte\")]")
  appendLine("        private static extern sbyte nuget_unwrap_byte(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_ubyte\")]")
  appendLine("        private static extern byte nuget_unwrap_ubyte(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_short\")]")
  appendLine("        private static extern short nuget_unwrap_short(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_ushort\")]")
  appendLine("        private static extern ushort nuget_unwrap_ushort(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_int\")]")
  appendLine("        private static extern int Native_unwrap_int(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_uint\")]")
  appendLine("        private static extern uint nuget_unwrap_uint(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_long\")]")
  appendLine("        private static extern long Native_unwrap_long(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_ulong\")]")
  appendLine("        private static extern ulong nuget_unwrap_ulong(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_float\")]")
  appendLine("        private static extern float Native_unwrap_float(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_double\")]")
  appendLine("        private static extern double Native_unwrap_double(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_bool\")]")
  appendLine("        private static extern bool Native_unwrap_bool(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_dispose\")]")
  appendLine("        private static extern void Native_dispose(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_string\")]")
  appendLine("        private static extern IntPtr nuget_wrap_string(string value);")
  appendLine()
  appendLine("        public static IntPtr WrapString(string value) => nuget_wrap_string(value);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_int\")]")
  appendLine("        private static extern IntPtr nuget_wrap_int(int value);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_long\")]")
  appendLine("        private static extern IntPtr nuget_wrap_long(long value);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_float\")]")
  appendLine("        private static extern IntPtr nuget_wrap_float(float value);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_double\")]")
  appendLine("        private static extern IntPtr nuget_wrap_double(double value);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_bool\")]")
  appendLine("        private static extern IntPtr nuget_wrap_bool(bool value);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"box_create_string\")]")
  appendLine("        private static extern IntPtr box_create_string(string value, out IntPtr error);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"box_create_byte\")]")
  appendLine("        private static extern IntPtr box_create_byte(sbyte value, out IntPtr error);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"box_create_ubyte\")]")
  appendLine("        private static extern IntPtr box_create_ubyte(byte value, out IntPtr error);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"box_create_short\")]")
  appendLine("        private static extern IntPtr box_create_short(short value, out IntPtr error);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"box_create_ushort\")]")
  appendLine("        private static extern IntPtr box_create_ushort(ushort value, out IntPtr error);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"box_create_int\")]")
  appendLine("        private static extern IntPtr box_create_int(int value, out IntPtr error);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"box_create_uint\")]")
  appendLine("        private static extern IntPtr box_create_uint(uint value, out IntPtr error);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"box_create_long\")]")
  appendLine("        private static extern IntPtr box_create_long(long value, out IntPtr error);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"box_create_ulong\")]")
  appendLine("        private static extern IntPtr box_create_ulong(ulong value, out IntPtr error);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"box_create_float\")]")
  appendLine("        private static extern IntPtr box_create_float(float value, out IntPtr error);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"box_create_double\")]")
  appendLine("        private static extern IntPtr box_create_double(double value, out IntPtr error);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"box_create_bool\")]")
  appendLine("        private static extern IntPtr box_create_bool(bool value, out IntPtr error);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"box_create_object\")]")
  appendLine("        private static extern IntPtr box_create_object(IntPtr value, out IntPtr error);")
  appendLine()
  appendLine("        public static T FromHandle<T>(IntPtr handle)")
  appendLine("        {")
  appendLine("            if (handle == IntPtr.Zero) return default!;")
  appendLine("            if (typeof(T) == typeof(string))")
  appendLine("            {")
  appendLine("                IntPtr strPtr = Native_unwrap_string(handle);")
  appendLine("                string result = Marshal.PtrToStringUTF8(strPtr)!;")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(sbyte))")
  appendLine("            {")
  appendLine("                sbyte result = nuget_unwrap_byte(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(byte))")
  appendLine("            {")
  appendLine("                byte result = nuget_unwrap_ubyte(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(short))")
  appendLine("            {")
  appendLine("                short result = nuget_unwrap_short(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(ushort))")
  appendLine("            {")
  appendLine("                ushort result = nuget_unwrap_ushort(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(int))")
  appendLine("            {")
  appendLine("                int result = Native_unwrap_int(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(uint))")
  appendLine("            {")
  appendLine("                uint result = nuget_unwrap_uint(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(long))")
  appendLine("            {")
  appendLine("                long result = Native_unwrap_long(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(ulong))")
  appendLine("            {")
  appendLine("                ulong result = nuget_unwrap_ulong(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(float))")
  appendLine("            {")
  appendLine("                float result = Native_unwrap_float(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(double))")
  appendLine("            {")
  appendLine("                double result = Native_unwrap_double(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(bool))")
  appendLine("            {")
  appendLine("                bool result = Native_unwrap_bool(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            return (T)Activator.CreateInstance(typeof(T),")
  appendLine("                System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Public,")
  appendLine("                null, new object[] { handle }, null)!;")
  appendLine("        }")
  appendLine()
  appendLine("        public static void Dispose(IntPtr handle) => Native_dispose(handle);")
  appendLine()
  appendLine("        public static IntPtr CreateBox<T>(T value)")
  appendLine("        {")
  appendLine("            IntPtr error;")
  appendLine("            IntPtr handle;")
  appendLine("            if (typeof(T) == typeof(string)) handle = box_create_string((string)(object)value!, out error);")
  appendLine("            else if (typeof(T) == typeof(sbyte)) handle = box_create_byte((sbyte)(object)value!, out error);")
  appendLine("            else if (typeof(T) == typeof(byte)) handle = box_create_ubyte((byte)(object)value!, out error);")
  appendLine("            else if (typeof(T) == typeof(short)) handle = box_create_short((short)(object)value!, out error);")
  appendLine("            else if (typeof(T) == typeof(ushort)) handle = box_create_ushort((ushort)(object)value!, out error);")
  appendLine("            else if (typeof(T) == typeof(int)) handle = box_create_int((int)(object)value!, out error);")
  appendLine("            else if (typeof(T) == typeof(uint)) handle = box_create_uint((uint)(object)value!, out error);")
  appendLine("            else if (typeof(T) == typeof(long)) handle = box_create_long((long)(object)value!, out error);")
  appendLine("            else if (typeof(T) == typeof(ulong)) handle = box_create_ulong((ulong)(object)value!, out error);")
  appendLine("            else if (typeof(T) == typeof(float)) handle = box_create_float((float)(object)value!, out error);")
  appendLine("            else if (typeof(T) == typeof(double)) handle = box_create_double((double)(object)value!, out error);")
  appendLine("            else if (typeof(T) == typeof(bool)) handle = box_create_bool((bool)(object)value!, out error);")
  appendLine("            else")
  appendLine("            {")
  appendLine("                var field = typeof(T).GetField(\"_handle\",")
  appendLine("                    System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Public);")
  appendLine("                if (field == null) throw new NotSupportedException($\"Cannot create Box<{typeof(T).Name}>\");")
  appendLine("                handle = box_create_object((IntPtr)field.GetValue(value)!, out error);")
  appendLine("            }")
  appendLine()
  appendLine("            if (error != IntPtr.Zero)")
  appendLine("            {")
  appendLine("                throw NugetErrorNative.BuildException(error);")
  appendLine("            }")
  appendLine("            return handle;")
  appendLine("        }")
  appendLine()
  appendLine("        public static IntPtr CreateList<T>(IEnumerable<T> values)")
  appendLine("        {")
  appendLine("            IntPtr listHandle = NugetListNative.Create();")
  appendLine("            foreach (T value in values)")
  appendLine("            {")
  appendLine("                if (typeof(T) == typeof(string)) NugetListNative.Add(listHandle, nuget_wrap_string((string)(object)value!));")
  appendLine("                else if (typeof(T) == typeof(int)) NugetListNative.Add(listHandle, nuget_wrap_int((int)(object)value!));")
  appendLine("                else if (typeof(T) == typeof(long)) NugetListNative.Add(listHandle, nuget_wrap_long((long)(object)value!));")
  appendLine("                else if (typeof(T) == typeof(float)) NugetListNative.Add(listHandle, nuget_wrap_float((float)(object)value!));")
  appendLine("                else if (typeof(T) == typeof(double)) NugetListNative.Add(listHandle, nuget_wrap_double((double)(object)value!));")
  appendLine("                else if (typeof(T) == typeof(bool)) NugetListNative.Add(listHandle, nuget_wrap_bool((bool)(object)value!));")
  appendLine("                else")
  appendLine("                {")
  appendLine("                    var field = typeof(T).GetField(\"_handle\",")
  appendLine("                        System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Public);")
  appendLine("                    if (field == null) throw new NotSupportedException($\"Cannot add {typeof(T).Name} to a Kotlin list\");")
  appendLine("                    NugetListNative.Add(listHandle, (IntPtr)field.GetValue(value)!);")
  appendLine("                }")
  appendLine("            }")
  appendLine("            return listHandle;")
  appendLine("        }")
  appendLine("    }")
  appendLine()
}

internal fun StringBuilder.renderListHelper(helper: CirListHelper) {
  appendLine("    internal static class NugetListNative")
  appendLine("    {")
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_list_count\")]")
  appendLine("        internal static extern int Count(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_list_get\")]")
  appendLine("        internal static extern IntPtr Get(IntPtr handle, int index);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_list_create\")]")
  appendLine("        internal static extern IntPtr Create();")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_list_add\")]")
  appendLine("        internal static extern void Add(IntPtr handle, IntPtr element);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_dispose\")]")
  appendLine("        internal static extern void Dispose(IntPtr handle);")
  appendLine("    }")
  appendLine()
}

internal fun StringBuilder.renderMapHelper(helper: CirMapHelper) {
  appendLine("    internal static class NugetMapNative")
  appendLine("    {")
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_map_count\")]")
  appendLine("        internal static extern int Count(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_map_key_at\")]")
  appendLine("        internal static extern IntPtr KeyAt(IntPtr handle, int index);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_map_value_at\")]")
  appendLine("        internal static extern IntPtr ValueAt(IntPtr handle, int index);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_dispose\")]")
  appendLine("        internal static extern void Dispose(IntPtr handle);")
  appendLine("    }")
  appendLine()
}

internal fun StringBuilder.renderSetHelper(helper: CirSetHelper) {
  appendLine("    internal static class NugetSetNative")
  appendLine("    {")
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_set_count\")]")
  appendLine("        internal static extern int Count(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_set_element_at\")]")
  appendLine("        internal static extern IntPtr ElementAt(IntPtr handle, int index);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_dispose\")]")
  appendLine("        internal static extern void Dispose(IntPtr handle);")
  appendLine("    }")
  appendLine()
}

