package io.github.xxfast.kotlin.native.nuget.processor.cir

internal fun StringBuilder.renderMarshalHelper(helper: CirMarshalHelper) {
  appendLine("    internal static class NugetMarshal")
  appendLine("    {")
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_string\")]")
  appendLine("        private static extern IntPtr Native_unwrap_string(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_byte\")]")
  appendLine("        private static extern sbyte nuget_unwrap_byte(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_ubyte\")]")
  appendLine("        private static extern byte nuget_unwrap_ubyte(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_short\")]")
  appendLine("        private static extern short nuget_unwrap_short(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_ushort\")]")
  appendLine("        private static extern ushort nuget_unwrap_ushort(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_int\")]")
  appendLine("        private static extern int Native_unwrap_int(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_uint\")]")
  appendLine("        private static extern uint nuget_unwrap_uint(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_long\")]")
  appendLine("        private static extern long Native_unwrap_long(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_ulong\")]")
  appendLine("        private static extern ulong nuget_unwrap_ulong(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_float\")]")
  appendLine("        private static extern float Native_unwrap_float(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_double\")]")
  appendLine("        private static extern double Native_unwrap_double(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_unwrap_bool\")]")
  appendLine("        private static extern bool Native_unwrap_bool(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_dispose\")]")
  appendLine("        private static extern void Native_dispose(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_string\")]")
  appendLine("        private static extern IntPtr nuget_wrap_string(string value);")
  appendLine()
  appendLine("        public static IntPtr WrapString(string value) => nuget_wrap_string(value);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_int\")]")
  appendLine("        private static extern IntPtr nuget_wrap_int(int value);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_long\")]")
  appendLine("        private static extern IntPtr nuget_wrap_long(long value);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_float\")]")
  appendLine("        private static extern IntPtr nuget_wrap_float(float value);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_double\")]")
  appendLine("        private static extern IntPtr nuget_wrap_double(double value);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_wrap_bool\")]")
  appendLine("        private static extern IntPtr nuget_wrap_bool(bool value);")
  appendLine()
  appendLine("        public static T FromHandle<T>(IntPtr handle)")
  appendLine("        {")
  appendLine("            if (handle == IntPtr.Zero) return default!;")
  appendLine("            // ADR-067: a nullable VALUE element (e.g. StateFlow<int?>) instantiates T as")
  appendLine("            // Nullable<int>; typeof(T) never equals typeof(int) for that T, so the plain")
  appendLine("            // per-primitive dispatch below would fall through to the Activator branch and")
  appendLine("            // throw MissingMethodException. Dispatch on the underlying type first, reusing")
  appendLine("            // the same box readers; a null reference element needs no such branch (its")
  appendLine("            // `default!` is already null and its non-null path constructs normally below).")
  appendLine("            Type? nullableUnderlying = Nullable.GetUnderlyingType(typeof(T));")
  appendLine("            if (nullableUnderlying != null)")
  appendLine("            {")
  appendLine("                if (nullableUnderlying == typeof(sbyte))")
  appendLine("                {")
  appendLine("                    sbyte result = nuget_unwrap_byte(handle);")
  appendLine("                    Native_dispose(handle);")
  appendLine("                    return (T)(object)result;")
  appendLine("                }")
  appendLine("                if (nullableUnderlying == typeof(byte))")
  appendLine("                {")
  appendLine("                    byte result = nuget_unwrap_ubyte(handle);")
  appendLine("                    Native_dispose(handle);")
  appendLine("                    return (T)(object)result;")
  appendLine("                }")
  appendLine("                if (nullableUnderlying == typeof(short))")
  appendLine("                {")
  appendLine("                    short result = nuget_unwrap_short(handle);")
  appendLine("                    Native_dispose(handle);")
  appendLine("                    return (T)(object)result;")
  appendLine("                }")
  appendLine("                if (nullableUnderlying == typeof(ushort))")
  appendLine("                {")
  appendLine("                    ushort result = nuget_unwrap_ushort(handle);")
  appendLine("                    Native_dispose(handle);")
  appendLine("                    return (T)(object)result;")
  appendLine("                }")
  appendLine("                if (nullableUnderlying == typeof(int))")
  appendLine("                {")
  appendLine("                    int result = Native_unwrap_int(handle);")
  appendLine("                    Native_dispose(handle);")
  appendLine("                    return (T)(object)result;")
  appendLine("                }")
  appendLine("                if (nullableUnderlying == typeof(uint))")
  appendLine("                {")
  appendLine("                    uint result = nuget_unwrap_uint(handle);")
  appendLine("                    Native_dispose(handle);")
  appendLine("                    return (T)(object)result;")
  appendLine("                }")
  appendLine("                if (nullableUnderlying == typeof(long))")
  appendLine("                {")
  appendLine("                    long result = Native_unwrap_long(handle);")
  appendLine("                    Native_dispose(handle);")
  appendLine("                    return (T)(object)result;")
  appendLine("                }")
  appendLine("                if (nullableUnderlying == typeof(ulong))")
  appendLine("                {")
  appendLine("                    ulong result = nuget_unwrap_ulong(handle);")
  appendLine("                    Native_dispose(handle);")
  appendLine("                    return (T)(object)result;")
  appendLine("                }")
  appendLine("                if (nullableUnderlying == typeof(float))")
  appendLine("                {")
  appendLine("                    float result = Native_unwrap_float(handle);")
  appendLine("                    Native_dispose(handle);")
  appendLine("                    return (T)(object)result;")
  appendLine("                }")
  appendLine("                if (nullableUnderlying == typeof(double))")
  appendLine("                {")
  appendLine("                    double result = Native_unwrap_double(handle);")
  appendLine("                    Native_dispose(handle);")
  appendLine("                    return (T)(object)result;")
  appendLine("                }")
  appendLine("                if (nullableUnderlying == typeof(bool))")
  appendLine("                {")
  appendLine("                    bool result = Native_unwrap_bool(handle);")
  appendLine("                    Native_dispose(handle);")
  appendLine("                    return (T)(object)result;")
  appendLine("                }")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(string))")
  appendLine("            {")
  appendLine("                IntPtr strPtr = Native_unwrap_string(handle);")
  appendLine("                string result = Marshal.PtrToStringUTF8(strPtr)!;")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(sbyte))")
  appendLine("            {")
  appendLine("                sbyte result = nuget_unwrap_byte(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(byte))")
  appendLine("            {")
  appendLine("                byte result = nuget_unwrap_ubyte(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(short))")
  appendLine("            {")
  appendLine("                short result = nuget_unwrap_short(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(ushort))")
  appendLine("            {")
  appendLine("                ushort result = nuget_unwrap_ushort(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(int))")
  appendLine("            {")
  appendLine("                int result = Native_unwrap_int(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(uint))")
  appendLine("            {")
  appendLine("                uint result = nuget_unwrap_uint(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(long))")
  appendLine("            {")
  appendLine("                long result = Native_unwrap_long(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(ulong))")
  appendLine("            {")
  appendLine("                ulong result = nuget_unwrap_ulong(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(float))")
  appendLine("            {")
  appendLine("                float result = Native_unwrap_float(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(double))")
  appendLine("            {")
  appendLine("                double result = Native_unwrap_double(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            if (typeof(T) == typeof(bool))")
  appendLine("            {")
  appendLine("                bool result = Native_unwrap_bool(handle);")
  appendLine("                Native_dispose(handle);")
  appendLine("                return (T)(object)result;")
  appendLine("            }")
  appendLine("            return (T)Activator.CreateInstance(typeof(T),")
  appendLine("                System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Public,")
  appendLine("                null, new object[] { handle }, null)!;")
  appendLine("        }")
  appendLine()
  appendLine("        public static void Dispose(IntPtr handle) => Native_dispose(handle);")
  appendLine()
  // ADR-073: the boxing switch shared by CreateList/CreateSet/CreateMap, so a future component
  // type is added in exactly one place.
  appendLine("        internal static IntPtr Wrap<T>(T value)")
  appendLine("        {")
  // ADR-083: the null pointer is the null component, for every component kind. The dispatch below
  // is on the *underlying* type because typeof(int?) != typeof(int), so without the normalization
  // a T of `int?` would miss every branch and fall into the reflective _handle fallback.
  appendLine("            if (value == null) return IntPtr.Zero;")
  appendLine("            var type = Nullable.GetUnderlyingType(typeof(T)) ?? typeof(T);")
  appendLine("            if (type == typeof(string)) return nuget_wrap_string((string)(object)value!);")
  appendLine("            if (type == typeof(int)) return nuget_wrap_int((int)(object)value!);")
  appendLine("            if (type == typeof(long)) return nuget_wrap_long((long)(object)value!);")
  appendLine("            if (type == typeof(float)) return nuget_wrap_float((float)(object)value!);")
  appendLine("            if (type == typeof(double)) return nuget_wrap_double((double)(object)value!);")
  appendLine("            if (type == typeof(bool)) return nuget_wrap_bool((bool)(object)value!);")
  appendLine("            var field = typeof(T).GetField(\"_handle\",")
  appendLine("                System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Public);")
  appendLine("            if (field == null) throw new NotSupportedException($\"Cannot pass {typeof(T).Name} to a Kotlin collection\");")
  appendLine("            return (IntPtr)field.GetValue(value)!;")
  appendLine("        }")
  appendLine()
  appendLine("        public static IntPtr CreateList<T>(IEnumerable<T> values)")
  appendLine("        {")
  appendLine("            IntPtr listHandle = NugetListNative.Create();")
  appendLine("            foreach (T value in values) NugetListNative.Add(listHandle, Wrap(value));")
  appendLine("            return listHandle;")
  appendLine("        }")
  appendLine()
  // Gated on helper.includesSet: NugetSetNative is only emitted when the tracker actually saw a
  // Set/MutableSet collection somewhere in the file, so this body must not exist unconditionally.
  if (helper.includesSet) {
    appendLine("        public static IntPtr CreateSet<T>(IEnumerable<T> values)")
    appendLine("        {")
    appendLine("            IntPtr setHandle = NugetSetNative.Create();")
    appendLine("            foreach (T value in values) NugetSetNative.Add(setHandle, Wrap(value));")
    appendLine("            return setHandle;")
    appendLine("        }")
    appendLine()
  }
  // Gated on helper.includesMap, mirroring includesSet above.
  if (helper.includesMap) {
    appendLine("        public static IntPtr CreateMap<TKey, TValue>(IEnumerable<KeyValuePair<TKey, TValue>> values)")
    appendLine("        {")
    appendLine("            IntPtr mapHandle = NugetMapNative.Create();")
    appendLine("            foreach (var pair in values) NugetMapNative.Put(mapHandle, Wrap(pair.Key), Wrap(pair.Value));")
    appendLine("            return mapHandle;")
    appendLine("        }")
    appendLine()
  }
  // ADR-040 sub-decision B: the one shared reflective helper for an interface-typed parameter
  // (e.g. `Cat.Befriend(IPet pet)`). The static parameter type is the projected interface, which
  // does not carry `_handle` (only the generated backing wrapper class does), so extraction is
  // reflective here rather than a direct field read.
  //
  // ADR-084 facet 3: no `_handle` means the value is C#-implemented, and the bridge factory turns
  // it into a Kotlin-side `object : Foo` handle so the ordinary handle path below it is reused
  // unchanged. Without a bridge layer in this module there is nothing to fall back to, so the
  // ADR-040 boundary exception stands.
  appendLine("        internal static IntPtr HandleOf(object value)")
  appendLine("        {")
  appendLine("            var field = value.GetType().GetField(\"_handle\",")
  appendLine("                System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Public);")
  appendLine("            if (field == null)")
  appendLine("            {")
  if (helper.includesBridge) {
    appendLine("                return NugetBridge.HandleFor(value);")
  } else {
    appendLine("                throw new NotSupportedException(")
    appendLine("                    $\"{value.GetType().Name} is not a Kotlin-backed object; passing a C#-implemented interface is not supported yet.\");")
  }
  appendLine("            }")
  appendLine("            return (IntPtr)field.GetValue(value)!;")
  appendLine("        }")
  appendLine()
  // ADR-084 stage 3: the same extraction, reporting whether it *minted* a transfer handle. A
  // Kotlin-backed wrapper's `_handle` belongs to that wrapper and must never be disposed here; a
  // bridge handle is a one-crossing transfer the call site frees once the native call returns.
  appendLine("        internal static IntPtr HandleOf(object value, out bool owned)")
  appendLine("        {")
  appendLine("            var field = value.GetType().GetField(\"_handle\",")
  appendLine("                System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Public);")
  appendLine("            if (field == null)")
  appendLine("            {")
  appendLine("                owned = true;")
  appendLine("                return HandleOf(value);")
  appendLine("            }")
  appendLine("            owned = false;")
  appendLine("            return (IntPtr)field.GetValue(value)!;")
  appendLine("        }")
  appendLine()
  appendLine("        internal static IntPtr HandleOfOrZero(object? value, out bool owned)")
  appendLine("        {")
  appendLine("            if (value == null)")
  appendLine("            {")
  appendLine("                owned = false;")
  appendLine("                return IntPtr.Zero;")
  appendLine("            }")
  appendLine("            return HandleOf(value, out owned);")
  appendLine("        }")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_csharp_token\")]")
  appendLine("        private static extern IntPtr Native_csharp_token(IntPtr handle);")
  appendLine()
  // ADR-084 facet 5: ask the handle whether a C# object is already behind it before wrapping it in
  // a second bridge. A Kotlin-backed object answers IntPtr.Zero and the caller wraps as before.
  appendLine("        internal static bool TryResolveCSharp<T>(IntPtr handle, out T original) where T : class")
  appendLine("        {")
  appendLine("            IntPtr token = Native_csharp_token(handle);")
  appendLine("            if (token == IntPtr.Zero)")
  appendLine("            {")
  appendLine("                original = null!;")
  appendLine("                return false;")
  appendLine("            }")
  // The returned StableRef was minted for this crossing only; the original object is reached
  // through the token, so the fresh handle would otherwise leak.
  appendLine("            Native_dispose(handle);")
  appendLine("            original = (T)GCHandle.FromIntPtr(token).Target!;")
  appendLine("            return true;")
  appendLine("        }")
  appendLine("    }")
  appendLine()
}

internal fun StringBuilder.renderListHelper(helper: CirListHelper) {
  appendLine("    internal static class NugetListNative")
  appendLine("    {")
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_list_count\")]")
  appendLine("        internal static extern int Count(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_list_get\")]")
  appendLine("        internal static extern IntPtr Get(IntPtr handle, int index);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_list_create\")]")
  appendLine("        internal static extern IntPtr Create();")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_list_add\")]")
  appendLine("        internal static extern void Add(IntPtr handle, IntPtr element);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_dispose\")]")
  appendLine("        internal static extern void Dispose(IntPtr handle);")
  appendLine("    }")
  appendLine()
}

internal fun StringBuilder.renderMapHelper(helper: CirMapHelper) {
  appendLine("    internal static class NugetMapNative")
  appendLine("    {")
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_map_count\")]")
  appendLine("        internal static extern int Count(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_map_key_at\")]")
  appendLine("        internal static extern IntPtr KeyAt(IntPtr handle, int index);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_map_value_at\")]")
  appendLine("        internal static extern IntPtr ValueAt(IntPtr handle, int index);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_map_create\")]")
  appendLine("        internal static extern IntPtr Create();")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_map_put\")]")
  appendLine("        internal static extern void Put(IntPtr handle, IntPtr key, IntPtr value);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_dispose\")]")
  appendLine("        internal static extern void Dispose(IntPtr handle);")
  appendLine("    }")
  appendLine()
}

internal fun StringBuilder.renderSetHelper(helper: CirSetHelper) {
  appendLine("    internal static class NugetSetNative")
  appendLine("    {")
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_set_count\")]")
  appendLine("        internal static extern int Count(IntPtr handle);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_set_element_at\")]")
  appendLine("        internal static extern IntPtr ElementAt(IntPtr handle, int index);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_set_create\")]")
  appendLine("        internal static extern IntPtr Create();")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_set_add\")]")
  appendLine("        internal static extern void Add(IntPtr handle, IntPtr element);")
  appendLine()
  appendLine("        [DllImport(\"${helper.libraryName}\", CallingConvention = CallingConvention.Cdecl, EntryPoint = \"nuget_dispose\")]")
  appendLine("        internal static extern void Dispose(IntPtr handle);")
  appendLine("    }")
  appendLine()
}

