package io.github.xxfast.kotlin.native.nuget.processor.tier1

/**
 * One [Tier1Harness.run] outcome: the real KSP2 run's diagnostics, whatever Kotlin source it
 * generated, and — when a `CNameExports.kt` was actually produced — the real JVM compiler's
 * diagnostics against it. Nothing here is a substring match target; assertions read
 * [compiledClean]/[compileErrors] (the **compile** mode), [generated] directly (the
 * **structural** mode, cell 14), or [kspErrors]/[kspWarnings] (the **diagnostic** mode, cell 23)
 * — see ADR-060 "Three assertion modes fall out of one harness".
 */
internal data class Tier1Result(
  val kspExitCode: String,
  val kspErrors: List<String>,
  val kspWarnings: List<String>,
  val generatedFiles: Map<String, String>,
  val compileErrors: List<String>,
  val compileWarnings: List<String>,
) {
  /** The generated bridge wrapper file (ADR-007's per-file naming always calls it this). */
  val generated: String
    get() = generatedFiles.entries.firstOrNull { it.key.endsWith("CNameExports.kt") }?.value
      ?: error(
        "CNameExports.kt was not generated by KSP2. kspExitCode=$kspExitCode " +
            "kspErrors=$kspErrors generatedFiles=${generatedFiles.keys}"
      )

  /**
   * The generated C# bindings file (`generateCSharpBindings()` in `NugetProcessor.kt`, always
   * named `Interop.cs`). Backs the **structural** assertion mode for the **C** cells (1, 8, 9,
   * 12) — asserting the C# text directly, never compiling it (ADR-060 "Rejected: compiling the
   * generated C# in Tier 1" — the forward direction needs no .NET SDK, MVP.md line 62).
   */
  val generatedCSharp: String
    get() = generatedFiles.entries.firstOrNull { it.key.endsWith("Interop.cs") }?.value
      ?: error(
        "Interop.cs was not generated by KSP2. kspExitCode=$kspExitCode " +
            "kspErrors=$kspErrors generatedFiles=${generatedFiles.keys}"
      )

  val compiledClean: Boolean
    get() = compileErrors.isEmpty()
}
